apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortress
  template:
    metadata:
      labels:
        app: fortress
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: fortress
          image: 584673484425.dkr.ecr.ap-south-1.amazonaws.com/fortress:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20